DR:
  active: true
  branch: New Mexico
  commission_rate: 30.0
  full_name: Daniel Rogers
  initials: DR
GV:
  active: true
  branch: New Mexico
  commission_rate: 28.0
  full_name: George Valenzuela
  initials: GV
MB:
  active: true
  branch: New Mexico
  commission_rate: 28.0
  full_name: 'Matthew Bercovitch '
  initials: MB
MG:
  active: true
  branch: New Mexico
  commission_rate: 30.0
  full_name: Mateo Grant
  initials: MG
MP:
  active: true
  branch: New Mexico
  commission_rate: 32.0
  full_name: Mark Garcia
  initials: MP
PE:
  active: true
  branch: New Mexico
  commission_rate: 33.0
  full_name: Parker Edwards
  initials: PE
