DR:
  active: true
  branch: New Mexico
  commission_rate: 30.0
  full_name: John Doe
  initials: DJ
GV:
  active: true
  branch: New Mexico
  commission_rate: 28.0
  full_name: Taylor Swift
  initials: TS
MB:
  active: true
  branch: New Mexico
  commission_rate: 28.0
  full_name: 'Johnny Appleseed '
  initials: JA
MG:
  active: true
  branch: New Mexico
  commission_rate: 30.0
  full_name: Tech 4
  initials: T4
MP:
  active: true
  branch: New Mexico
  commission_rate: 32.0
  full_name: Jane Doe
  initials: JD

